# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'vlcjuncook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MobileVLCKit'

  # Pods for vlcjuncook

  target 'vlcjuncookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vlcjuncookUITests' do
    # Pods for testing
  end

end
